services:
  dev:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    command: -i -c "while :; do sleep 10; done"
    volumes:
      - .:/workspace:cached
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - DATABASE_URL=${POSTGRES_URL}
    networks:
      - my-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    networks:
      - my-network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  db_data: