services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    entrypoint: /bin/bash
    command: -i -c "while :; do sleep 10; done"
    volumes:
      - .:/workspace:cached
    env_file:
      - .env
    networks:
      - my-network

  db:
    image: postgres:15-alpine
    networks:
      - my-network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  my-network:
    driver: bridge

volumes:
  db_data: